package rules 

import java.util.*
import java.math.*

global List results

dialect "mvel"

declare  Model_8b 

    name_8 : Number  
end


rule "multiple_condition0"
    activation-group "3.multiple_condition"
    salience 3
    date-effective "01-Jan-2021 0:0:0.0"
    date-expires "31-Dec-2021 23:59:59.999"
    enabled true
when
    $Model_8b : Model_8b(  )  
    Object( (($Model_8b.name_8 >= 0 && $Model_8b.name_8 < 10)) )  
then
results.add("10")

end

rule "multiple_condition1"
    activation-group "3.multiple_condition"
    salience 2
    date-effective "01-Jan-2021 0:0:0.0"
    date-expires "31-Dec-2021 23:59:59.999"
    enabled true
when
    $Model_8b : Model_8b(  )  
    Object( (($Model_8b.name_8 >= 10 && $Model_8b.name_8 < 100)) )  
then
results.add("100")

end

rule "multiple_condition2"
    activation-group "3.multiple_condition"
    salience 1
    date-effective "01-Jan-2021 0:0:0.0"
    date-expires "31-Dec-2021 23:59:59.999"
    enabled true
when
    Object(  )  
then
results.add("0")

end


