package rules 

import java.util.*
import java.math.*

global List results

dialect "mvel"

declare  Model_Data 

    field_int : Integer  
    field_string : String  
    field_byte : Byte  
    field_long : Long  
    field_float : Float  
    field_date : Date  
    field_big_decimal : BigDecimal  
    field_double : Double  
    field_short : Short  
    field_boolean : Boolean  
    field_number : Number  
end


rule "operator-in0"
    activation-group "3.operator-in"
    salience 2
    date-effective "01-Jan-2021 0:0:0.0"
    date-expires "31-Dec-2021 23:59:59.0"
    enabled true
when
    $Model_Data : Model_Data(  )  
    Object( (($Model_Data.field_string in ("string1","string2","string3") && $Model_Data.field_number in (100,200,300))) )  
then
results.add("ACTION")

end

rule "operator-in1"
    activation-group "3.operator-in"
    salience 1
    date-effective "01-Jan-2021 0:0:0.0"
    date-expires "31-Dec-2021 23:59:59.0"
    enabled true
when
    Object(  )  
then
results.add("")

end


